[pytest]
filterwarnings =
    ignore:.*oneOf.*deprecated.*:Warning
    ignore:.*parseString.*deprecated.*:Warning
    ignore:.*resetCache.*deprecated.*:Warning
    ignore:.*enablePackrat.*deprecated.*:Warning
    ignore:.*divide by zero encountered in matmul.*:RuntimeWarning
    ignore:.*overflow encountered in matmul.*:RuntimeWarning
    ignore:.*invalid value encountered in matmul.*:RuntimeWarning

